version: '3.7'

services:

  api:
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    restart: always
    command: yarn dev
    tty: true
    stdin_open: true
    expose: 
      - "3000"
    build:
      context: ../.
      dockerfile: ./docker/dev/Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ../.:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    healthcheck:
      disable: false

