version: '3.7'

services:

  api:
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
    restart: always
    expose: 
      - "8080"
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        - NODE_ENV=production
    command: npm start
    volumes:
      - .:/usr/app:delegated
      - /usr/app/node_modules
    working_dir: /app
    healthcheck:
      disable: false

