version: '3.7'

services:

  api:
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      PORT: 8080
    restart: always
    command: yarn start
    tty: true
    stdin_open: true
    expose: 
      - "8080"
    build:
      context: ../.
      dockerfile: ./docker/prod/Dockerfile
      args:
        - NODE_ENV=production
    volumes:
      - ../.:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    healthcheck:
      disable: false

